use_frameworks!

target 'BubblesView_Example' do
  pod 'BubblesView', :path => '../'
  pod 'HSLuvSwift', :git => 'https://github.com/nickswalker/hsluv-swift.git', :branch => 'master'
  
  target 'BubblesView_Tests' do
    inherit! :search_paths

    
  end
end
